# Generated by Django 5.0.4 on 2025-05-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreadhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
